### ISSUE TITLE
Update Locals lab to create a new directory to limit confusion on which files to edit

### ISSUE THREAD

**Issue by rptdata** [rptcloud/azure_terraform#10]
Update Locals lab to create a new directory to limit confusion on which files to edit

https://github.com/rptcloud/azure_terraform/blob/main/locals.md

**Comment by gmaentz** [comment]
Complete - https://github.com/rptcloud/azure_terraform/commit/d3aba45ba7df6ef6e9fdee2e136365c83b13b7f1
