### ISSUE TITLE
Update templatefile lab to remove deprecated resource

### ISSUE THREAD

**Issue by rptdata** [rptcloud/azure_terraform#9]
The `azurerm_dashboard` resource is deprecated and will be removed in v4.0 of the AzureRM Provider - the replacement is available as
│ `azurerm_portal_dashboard`.

**Comment by gmaentz** [comment]
https://github.com/rptcloud/azure_terraform/commit/ab01783935d38e7a8cd57d50112f64ca134236d0

https://github.com/rptcloud/azure_terraform/commit/007e4cc893cc17ac4222b246cd7c39af753732c3
